# Generated by Django 3.2.7 on 2021-10-04 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.CharField(max_length=250)),
                ('localisation', models.CharField(max_length=250)),
                ('detail_infos', models.TextField(blank=True, null=True)),
                ('telephone', models.TextField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('proprietaire', models.CharField(max_length=250)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='Nom Complet')),
                ('telephone', models.CharField(max_length=250, verbose_name='Numero de Telephone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu_depart', models.CharField(max_length=250)),
                ('lieu_arrive', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField()),
                ('date_heure_depart', models.DateTimeField()),
                ('places', models.IntegerField()),
                ('itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='agence.agence')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agence.client')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agence.programme')),
            ],
        ),
    ]
