# Generated by Django 3.2.7 on 2021-10-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agence',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
