# Generated by Django 3.2.7 on 2021-10-04 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0002_alter_agence_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='itineraire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraires', to='agence.itineraire'),
        ),
    ]
