# Generated by Django 3.2.7 on 2021-10-04 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0003_alter_programme_itineraire'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraire',
            name='agence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agence.agence'),
            preserve_default=False,
        ),
    ]
