# Generated by Django 3.2.8 on 2021-10-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0004_itineraire_agence'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='paye',
            field=models.BooleanField(default=False),
        ),
    ]
