# Generated by Django 3.2.8 on 2021-10-08 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0005_reservation_paye'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='date_heure_depart',
        ),
        migrations.AddField(
            model_name='programme',
            name='date_depart',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programme',
            name='heure_depart',
            field=models.TimeField(default='7:20'),
            preserve_default=False,
        ),
    ]
