# Generated by Django 3.2.8 on 2021-10-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0006_auto_20211008_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='heure_depart',
            field=models.DateField(),
        ),
    ]
