# Generated by Django 3.2.8 on 2021-10-12 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0008_alter_programme_heure_depart'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='places',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='programme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agence.programme'),
            preserve_default=False,
        ),
    ]
