# Generated by Django 3.2.8 on 2021-10-12 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0009_auto_20211012_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='places',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agence.programme'),
        ),
    ]
