# Generated by Django 3.2.8 on 2021-10-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0010_auto_20211012_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='places_libres',
            field=models.IntegerField(default=0),
        ),
    ]
