# Generated by Django 3.2.8 on 2021-10-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0011_programme_places_libres'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
