# Generated by Django 3.2.7 on 2021-09-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='price',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
